
The following have been reloaded with a version change:
  1) python/2.7.14_openmpi-2.0.1 => python/3.7.0


The following have been reloaded with a version change:
  1) zlib/1.2.11 => zlib/1.2.11_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18 => hdf5/1.8.18_parallel_studio-2017.1
  2) szip/2.1.1 => szip/2.1.1_parallel_studio-2017.1
  3) zlib/1.2.11_parallel_studio-2017.1 => zlib/1.2.11


The following have been reloaded with a version change:
  1) openmpi/2.0.1_gcc-4.8.5 => openmpi/2.0.1_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18_parallel_studio-2017.1 => hdf5/1.8.18
  2) openmpi/2.0.1_parallel_studio-2017.1 => openmpi/2.1.2_gcc-4.8.5
  3) python/3.7.0 => python/2.7.14_openmpi-2.1.2
  4) szip/2.1.1_parallel_studio-2017.1 => szip/2.1.1

Traceback (most recent call last):
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "asynchdist_assim_parallel_simp.py", line 39, in <module>
    state = assim.advance(buffer_size)
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 560, in advance
    outvec = np.expand_dims(np.reshape(outarray,(num_steps+1,-1))[1:,:].flatten(),1)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/numpy-1.13.3-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/numpy-1.13.3-py2.7-linux-x86_64.egg/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 614784 into shape (49,newaxis)
[argon-lc-i18-20:15726] *** Process received signal ***
[argon-lc-i18-20:15726] Signal: Segmentation fault (11)
[argon-lc-i18-20:15726] Signal code: Address not mapped (1)
[argon-lc-i18-20:15726] Failing at address: 0x48
[argon-lc-i18-20:15726] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2ae0009626d0]
[argon-lc-i18-20:15726] [ 1] /Users/apensoneault/asynch_python/libs/libasynch_py.so(Flush_TransData+0x3c)[0x2ae036b47e8c]
[argon-lc-i18-20:15726] [ 2] /Users/apensoneault/asynch_python/libs/libasynch_py.so(TransData_Free+0x2e)[0x2ae036b47c9e]
[argon-lc-i18-20:15726] [ 3] /Users/apensoneault/asynch_python/libs/libasynch_py.so(Asynch_Free+0x23)[0x2ae036b5c493]
[argon-lc-i18-20:15726] [ 4] /opt/apps/libffi/3.2.1/lib64/libffi.so.6(ffi_call_unix64+0x4c)[0x2ae00effeeaa]
[argon-lc-i18-20:15726] [ 5] /opt/apps/libffi/3.2.1/lib64/libffi.so.6(ffi_call+0x165)[0x2ae00effe015]
[argon-lc-i18-20:15726] [ 6] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x27b)[0x2ae00edea51b]
[argon-lc-i18-20:15726] [ 7] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/lib-dynload/_ctypes.so(+0x9515)[0x2ae00ede1515]
[argon-lc-i18-20:15726] [ 8] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x2ae000585663]
[argon-lc-i18-20:15726] [ 9] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x3aa6)[0x2ae00063b156]
[argon-lc-i18-20:15726] [10] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d)[0x2ae000640e5d]
[argon-lc-i18-20:15726] [11] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x86500)[0x2ae0005b7500]
[argon-lc-i18-20:15726] [12] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x2ae000585663]
[argon-lc-i18-20:15726] [13] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x6319d)[0x2ae00059419d]
[argon-lc-i18-20:15726] [14] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x2ae000585663]
[argon-lc-i18-20:15726] [15] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47)[0x2ae0006370b7]
[argon-lc-i18-20:15726] [16] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x64581)[0x2ae000595581]
[argon-lc-i18-20:15726] [17] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9948f)[0x2ae0005ca48f]
[argon-lc-i18-20:15726] [18] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9948f)[0x2ae0005ca48f]
[argon-lc-i18-20:15726] [19] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x6466b)[0x2ae00059566b]
[argon-lc-i18-20:15726] [20] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9897f)[0x2ae0005c997f]
[argon-lc-i18-20:15726] [21] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyDict_SetItem+0x7b)[0x2ae0005cc7db]
[argon-lc-i18-20:15726] [22] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(_PyModule_Clear+0x14c)[0x2ae0005d0d3c]
[argon-lc-i18-20:15726] [23] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9fd88)[0x2ae0005d0d88]
[argon-lc-i18-20:15726] [24] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9948f)[0x2ae0005ca48f]
[argon-lc-i18-20:15726] [25] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0xba0d6)[0x2ae0005eb0d6]
[argon-lc-i18-20:15726] [26] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x852a2)[0x2ae0005b62a2]
[argon-lc-i18-20:15726] [27] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x1422ab)[0x2ae0006732ab]
[argon-lc-i18-20:15726] [28] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x1422bb)[0x2ae0006732bb]
[argon-lc-i18-20:15726] [29] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x1422bb)[0x2ae0006732bb]
[argon-lc-i18-20:15726] *** End of error message ***
