
The following have been reloaded with a version change:
  1) python/2.7.14_openmpi-2.0.1 => python/3.7.0


The following have been reloaded with a version change:
  1) zlib/1.2.11 => zlib/1.2.11_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18 => hdf5/1.8.18_parallel_studio-2017.1
  2) szip/2.1.1 => szip/2.1.1_parallel_studio-2017.1
  3) zlib/1.2.11_parallel_studio-2017.1 => zlib/1.2.11


The following have been reloaded with a version change:
  1) openmpi/2.0.1_gcc-4.8.5 => openmpi/2.0.1_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18_parallel_studio-2017.1 => hdf5/1.8.18
  2) openmpi/2.0.1_parallel_studio-2017.1 => openmpi/2.1.2_gcc-4.8.5
  3) python/3.7.0 => python/2.7.14_openmpi-2.1.2
  4) szip/2.1.1_parallel_studio-2017.1 => szip/2.1.1

Traceback (most recent call last):
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Traceback (most recent call last):
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
    "__main__", fname, loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    exec code in run_globals
    main()
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    main()
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
    run_command_line(args)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 252, in run_path
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 82, in _run_module_code
    exec code in run_globals
    mod_name, mod_fname, mod_loader, pkg_name)
  File "asynchdist_assim_parallel_simp.py", line 14, in <module>
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "asynchdist_assim_parallel_simp.py", line 14, in <module>
    assim = Assim(sys.argv[1])
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 427, in __init__
    assim = Assim(sys.argv[1])
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 427, in __init__
    self.asynch_data = self.get_asynch_params(filename)
    self.asynch_data = self.get_asynch_params(filename)
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 505, in get_asynch_params
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 505, in get_asynch_params
    asynch_data = get_asynch_params(filename) 
  File "/Users/apensoneault/asynch_python/asynch_py/io.py", line 115, in get_asynch_params
    asynch_data = get_asynch_params(filename) 
  File "/Users/apensoneault/asynch_python/asynch_py/io.py", line 115, in get_asynch_params
    data = read_json(filename)
  File "/Users/apensoneault/asynch_python/asynch_py/io.py", line 73, in read_json
    data = read_json(filename)
  File "/Users/apensoneault/asynch_python/asynch_py/io.py", line 73, in read_json
    with open(filename) as f:
IOError    with open(filename) as f:
IOError: [Errno 2] No such file or directory: './jsons/test': [Errno 2] No such file or directory: './jsons/test'

[argon-lc-i18-21.hpc:08602] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[argon-lc-i18-21.hpc:08602] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
