
The following have been reloaded with a version change:
  1) zlib/1.2.11 => zlib/1.2.11_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18 => hdf5/1.8.18_parallel_studio-2017.1
  2) szip/2.1.1 => szip/2.1.1_parallel_studio-2017.1
  3) zlib/1.2.11_parallel_studio-2017.1 => zlib/1.2.11


The following have been reloaded with a version change:
  1) openmpi/2.0.1_gcc-4.8.5 => openmpi/2.0.1_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18_parallel_studio-2017.1 => hdf5/1.8.18
  2) openmpi/2.0.1_parallel_studio-2017.1 => openmpi/2.1.2_gcc-4.8.5
  3) python/3.7.0 => python/2.7.14_openmpi-2.1.2
  4) szip/2.1.1_parallel_studio-2017.1 => szip/2.1.1

Traceback (most recent call last):
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "asynchdist_assim_parallel_simp.py", line 39, in <module>
    state = assim.advance(buffer_size)
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 597, in advance
Traceback (most recent call last):
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "asynchdist_assim_parallel_simp.py", line 39, in <module>
    state = assim.advance(buffer_size)
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 597, in advance
    raise ValueError('Incorrect size of output, size='+str(len(outarray)))
ValueError: Incorrect size of output, size=0
    raise ValueError('Incorrect size of output, size='+str(len(outarray)))
ValueError: Incorrect size of output, size=0
[argon-lc-g11-40.hpc:26422] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[argon-lc-g11-40.hpc:26422] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
