
The following have been reloaded with a version change:
  1) python/2.7.14_openmpi-2.0.1 => python/3.7.0


The following have been reloaded with a version change:
  1) zlib/1.2.11 => zlib/1.2.11_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18 => hdf5/1.8.18_parallel_studio-2017.1
  2) szip/2.1.1 => szip/2.1.1_parallel_studio-2017.1
  3) zlib/1.2.11_parallel_studio-2017.1 => zlib/1.2.11


The following have been reloaded with a version change:
  1) openmpi/2.0.1_gcc-4.8.5 => openmpi/2.0.1_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18_parallel_studio-2017.1 => hdf5/1.8.18
  2) openmpi/2.0.1_parallel_studio-2017.1 => openmpi/2.1.2_gcc-4.8.5
  3) python/3.7.0 => python/2.7.14_openmpi-2.1.2
  4) szip/2.1.1_parallel_studio-2017.1 => szip/2.1.1

Traceback (most recent call last):
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "asynchdist_assim_parallel_simp.py", line 39, in <module>
    state = assim.advance(buffer_size)
  File "/Users/apensoneault/asynch_python/asynch_py/asynch_interface_parallel.py", line 614, in advance
    print('Incorrect size of output in run ' + str(n) + ', size='+str(len(outarray)+', retrying'))
TypeError: unsupported operand type(s) for +: 'int' and 'str'
[argon-lc-g11-26:37535] *** Process received signal ***
[argon-lc-g11-26:37535] Signal: Segmentation fault (11)
[argon-lc-g11-26:37535] Signal code: Address not mapped (1)
[argon-lc-g11-26:37535] Failing at address: 0x48
[argon-lc-g11-26:37535] [ 0] /lib64/libpthread.so.0(+0xf6d0)[0x2afcdc0316d0]
[argon-lc-g11-26:37535] [ 1] /Users/apensoneault/asynch_python/libs/libasynch_py.so(Flush_TransData+0x2d)[0x2afd26d21774]
[argon-lc-g11-26:37535] [ 2] /Users/apensoneault/asynch_python/libs/libasynch_py.so(TransData_Free+0x1a1)[0x2afd26d21b17]
[argon-lc-g11-26:37535] [ 3] /Users/apensoneault/asynch_python/libs/libasynch_py.so(Asynch_Free+0x2c)[0x2afd26d3381f]
[argon-lc-g11-26:37535] [ 4] /opt/apps/libffi/3.2.1/lib64/libffi.so.6(ffi_call_unix64+0x4c)[0x2afcea6cdeaa]
[argon-lc-g11-26:37535] [ 5] /opt/apps/libffi/3.2.1/lib64/libffi.so.6(ffi_call+0x165)[0x2afcea6cd015]
[argon-lc-g11-26:37535] [ 6] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x27b)[0x2afcea4b951b]
[argon-lc-g11-26:37535] [ 7] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/python2.7/lib-dynload/_ctypes.so(+0x9515)[0x2afcea4b0515]
[argon-lc-g11-26:37535] [ 8] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x2afcdbc54663]
[argon-lc-g11-26:37535] [ 9] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x3aa6)[0x2afcdbd0a156]
[argon-lc-g11-26:37535] [10] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x80d)[0x2afcdbd0fe5d]
[argon-lc-g11-26:37535] [11] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x86500)[0x2afcdbc86500]
[argon-lc-g11-26:37535] [12] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x2afcdbc54663]
[argon-lc-g11-26:37535] [13] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x6319d)[0x2afcdbc6319d]
[argon-lc-g11-26:37535] [14] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyObject_Call+0x43)[0x2afcdbc54663]
[argon-lc-g11-26:37535] [15] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47)[0x2afcdbd060b7]
[argon-lc-g11-26:37535] [16] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x64581)[0x2afcdbc64581]
[argon-lc-g11-26:37535] [17] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9948f)[0x2afcdbc9948f]
[argon-lc-g11-26:37535] [18] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9948f)[0x2afcdbc9948f]
[argon-lc-g11-26:37535] [19] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x6466b)[0x2afcdbc6466b]
[argon-lc-g11-26:37535] [20] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9897f)[0x2afcdbc9897f]
[argon-lc-g11-26:37535] [21] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(PyDict_SetItem+0x7b)[0x2afcdbc9b7db]
[argon-lc-g11-26:37535] [22] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(_PyModule_Clear+0x14c)[0x2afcdbc9fd3c]
[argon-lc-g11-26:37535] [23] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9fd88)[0x2afcdbc9fd88]
[argon-lc-g11-26:37535] [24] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x9948f)[0x2afcdbc9948f]
[argon-lc-g11-26:37535] [25] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0xba0d6)[0x2afcdbcba0d6]
[argon-lc-g11-26:37535] [26] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x852a2)[0x2afcdbc852a2]
[argon-lc-g11-26:37535] [27] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x1422ab)[0x2afcdbd422ab]
[argon-lc-g11-26:37535] [28] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x1422bb)[0x2afcdbd422bb]
[argon-lc-g11-26:37535] [29] /opt/apps/python/2.7.14_openmpi-2.1.2/lib/libpython2.7.so.1.0(+0x1422bb)[0x2afcdbd422bb]
[argon-lc-g11-26:37535] *** End of error message ***
